[package]
name = "mazes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
tiny-skia = "0.11.2"
nom = "7.1.3"
partitions = "0.2.4"
indicatif = "0.17.7"